### ISSUE TITLE
Warnings after update to js-controller 3

### ISSUE THREAD

**Issue by mk176** [ioBroker/ioBroker.onkyo#48]
Since upgrade to js-controller 3 i've got lot of warnings in the log and that i should inform the dev.

2020-04-23 19:58:53.722  - warn:  onkyo.0 (20236) Object onkyo.0.Zone1 is invalid: obj.type has an  invalid value (object) but has to be one of state, channel, device,  enum, host, adapter, instance, meta, config, script, user, group, chart,  folder
--
2020-04-23 19:58:53.724  - warn: onkyo.0 (20236) This object will not be created in future versions. Please report this to the developer.
2020-04-23 19:58:53.725  - warn:  onkyo.0 (20236) Object onkyo.0.Zone2 is invalid: obj.type has an  invalid value (object) but has to be one of state, channel, device,  enum, host, adapter, instance, meta, config, script, user, group, chart,  folder
2020-04-23 19:58:53.726  - warn: onkyo.0 (20236) This object will not be created in future versions. Please report this to the developer.
2020-04-23 19:58:53.728  - warn:  onkyo.0 (20236) Object onkyo.0.Zone3 is invalid: obj.type has an  invalid value (object) but has to be one of state, channel, device,  enum, host, adapter, instance, meta, config, script, user, group, chart,  folder
2020-04-23 19:58:53.729  - warn: onkyo.0 (20236) This object will not be created in future versions. Please report this to the developer.
2020-04-23 19:58:53.759  - warn:  onkyo.0 (20236) Object onkyo.0.Device.MediaState is invalid:  obj.common.type has an invalid value (text) but has to be one of number,  string, boolean, array, object, mixed, file, json
2020-04-23 19:58:53.759  - warn: onkyo.0 (20236) This object will not be created in future versions. Please report this to the developer.
2020-04-23 19:58:53.779  - warn:  onkyo.0 (20236) Object onkyo.0.Device.CoverBase64 is invalid:  obj.common.type has an invalid value (media.cover) but has to be one of  number, string, boolean, array, object, mixed, file, json

**Comment by FredF63** [comment]
Same warnings here

**Comment by Pittini** [comment]
Same here:


onkyo.0 | 2021-01-30 21:03:40.111 | warn | (12439) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
onkyo.0 | 2021-01-30 21:03:40.111 | warn | (12439) Object onkyo.0.Device.CoverURL is invalid: obj.common.type has an invalid value (media.cover) but has to be one of number, string, boolean, array, object, mixed, file, json
onkyo.0 | 2021-01-30 21:03:40.063 | warn | (12439) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-01-30 21:03:40.063 | warn | (12439) Object onkyo.0.Device.CoverBase64 is invalid: obj.common.type has an invalid value (media.cover) but has to be one of number, string, boolean, array, object, mixed, file, json
onkyo.0 | 2021-01-30 21:03:39.421 | warn | (12439) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-01-30 21:03:39.420 | warn | (12439) Object onkyo.0.Device.MediaState is invalid: obj.common.type has an invalid value (text) but has to be one of number, string, boolean, array, object, mixed, file, json
onkyo.0 | 2021-01-30 21:03:38.445 | warn | (12439) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-01-30 21:03:38.444 | warn | (12439) Object onkyo.0.Zone3 is invalid: obj.type has an invalid value (object) but has to be one of state, channel, device, enum, host, adapter, instance, meta, config, script, user, group, chart, f
onkyo.0 | 2021-01-30 21:03:38.441 | warn | (12439) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-01-30 21:03:38.440 | warn | (12439) Object onkyo.0.Zone2 is invalid: obj.type has an invalid value (object) but has to be one of state, channel, device, enum, host, adapter, instance, meta, config, script, user, group, chart, f
onkyo.0 | 2021-01-30 21:03:38.436 | warn | (12439) This object will not be created in future versions. Please report this to the developer.
onkyo.0 | 2021-01-30 21:03:38.435 | warn | (12439) Object onkyo.0.Zone1 is invalid: obj.type has an invalid value (object) but has to be one of state, channel, device, enum, host, adapter, instance, meta, config, script, user, group, chart, f

**Comment by Diginix** [comment]
I got only this warning for missing object. As workaround I have created it with type string.
> 2021-02-02 17:53:01.113  - warn: onkyo.0 (1271465) State "onkyo.0.NET_Shuffle_Status" has no existing object, this might lead to an error in future versions

But my Onkyo adapter instance crashs complete because of missing BMP image for VIS, but I don't use the VIS adapter: 
> 2021-02-02 17:53:03.328  - error: onkyo.0 (1271465) uncaught exception: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/files/vis/CoverImage.bmp'
> 2021-02-02 17:53:03.331  - error: onkyo.0 (1271465) Error: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/files/vis/CoverImage.bmp'
>     at Object.openSync (fs.js:462:3)
>     at Object.writeFileSync (fs.js:1384:35)
>     at EventEmitter.<anonymous> (/opt/iobroker/node_modules/iobroker.onkyo/main.js:999:7)
>     at EventEmitter.emit (events.js:314:20)
>     at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.onkyo/node_modules/eiscp/eiscp.js:384:8)
>     at Socket.emit (events.js:314:20)
>     at addChunk (_stream_readable.js:297:12)
>     at readableAddChunk (_stream_readable.js:272:9)
>     at Socket.Readable.push (_stream_readable.js:213:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
> 2021-02-02 17:53:03.331  - error: onkyo.0 (1271465) Exception-Code: ENOENT: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/files/vis/CoverImage.bmp'
> 2021-02-02 17:53:03.372  - info: onkyo.0 (1271465) terminating
> 2021-02-02 17:53:03.374  - warn: onkyo.0 (1271465) Terminated (UNCAUGHT_EXCEPTION): Without reason
> 2021-02-02 17:53:03.375  - info: onkyo.0 (1271465) AVR disconnected
> 2021-02-02 17:53:03.381  - warn: onkyo.0 (1271465) State "onkyo.0.connected" has no existing object, this might lead to an error in future versions

**Comment by Apollon77** [comment]
The main issue is that the adapter at all writes directly there ...

**Comment by Apollon77** [comment]
@Eisbaeeer this could be adjusted to adapter.writefile('vis','filename...) but needs a try/catch or error callback in order to catch the error that vis was not installed and so the folder does not exist. Could you take a look I could only make that change 100% blind

**Comment by Pittini** [comment]
push
